language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.1
os:
  - linux
  - osx
install:
  - ./build/install.sh
  - if [ "$(uname -s)" != "Darwin" ]; then sudo apt-get update && sudo apt-get install -y zsh; fi
script:
  - ./script/test
git:
  submodules: false
